### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by KSepetanc** [PeaceFounder/AppBundler.jl#26]
I am building UI app with AppBundler on Windows. Build script passes without errors, but when the app is installed and run, it silently crashes. The crash is caused by `import MyCustomPackage` command right after `import QML` in the UI script. I've put significant effort to get crash log that I show below. Import fails to load some of the libraries related to use of HSL_jll.jl. My package (which has HSL_jll.jl dependency) otherwise works normally both from REPL and compiles and runs correctly using PackageCompiler (create_app command). Is this a know bug? Is this maybe related to lazy artifacts? How to approach this?

I am using Julia 1.11.7 and HSL_jll is specified using [sources] in project.toml so it is not the placeholder package.

```
InitError: could not load library "C:\Users\karlo\AppData\Local\Temp\jl_CAQOVC\share\julia\stdlib\v1.11\HSL_jll\override\bin\x86_64-w64-mingw32-libgfortran5\libhsl.dll"
The specified module could not be found. 
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl .\libdl.jl:120
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl .\libdl.jl:119
  [3] macro expansion
    @ C:\Users\karlo\AppData\Local\Temp\jl_CAQOVC\share\julia\stdlib\v1.11\JLLWrappers\src\products\library_generators.jl:63 [inlined]
  [4] __init__()
    @ HSL_jll C:\Users\karlo\AppData\Local\Temp\jl_CAQOVC\share\julia\stdlib\v1.11\HSL_jll\src\wrappers\x86_64-w64-mingw32-libgfortran5.jl:13
  [5] run_module_init(mod::Module, i::Int64)
    @ Base .\loading.jl:1378
  [6] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base .\loading.jl:1366
  [7] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any}, ignore_native::Nothing; register::Bool)
    @ Base .\loading.jl:1254
  [8] _include_from_serialized (repeats 2 times)
    @ .\loading.jl:1210 [inlined]
  [9] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128, stalecheck::Bool; reasons::Dict{String, Int64}, DEPOT_PATH::Vector{String})
    @ Base .\loading.jl:2041
 [10] _require(pkg::Base.PkgId, env::String)
    @ Base .\loading.jl:2527
 [11] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:2388
 [12] #invoke_in_world#3
    @ .\essentials.jl:1089 [inlined]
 [13] invoke_in_world
    @ .\essentials.jl:1086 [inlined]
 [14] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:2375
 [15] macro expansion
    @ .\loading.jl:2314 [inlined]
 [16] macro expansion
    @ .\lock.jl:273 [inlined]
 [17] __require(into::Module, mod::Symbol)
    @ Base .\loading.jl:2271
 [18] #invoke_in_world#3
    @ .\essentials.jl:1089 [inlined]
 [19] invoke_in_world
    @ .\essentials.jl:1086 [inlined]
 [20] require
    @ .\loading.jl:2260 [inlined]
 [21] (::App.var"#3#6"{IOStream})()
    @ App C:\Users\karlo\AppData\Local\Temp\jl_CAQOVC\share\julia\stdlib\v1.11\App\src\App.jl:20
 [22] (::Base.RedirectStdStream)(thunk::App.var"#3#6"{IOStream}, stream::IOStream)
    @ Base .\stream.jl:1464
 [23] #2
    @ C:\Users\karlo\AppData\Local\Temp\jl_CAQOVC\share\julia\stdlib\v1.11\App\src\App.jl:11 [inlined]
 [24] (::Base.RedirectStdStream)(thunk::App.var"#2#5"{IOStream}, stream::IOStream)
    @ Base .\stream.jl:1464
 [25] #1
    @ C:\Users\karlo\AppData\Local\Temp\jl_CAQOVC\share\julia\stdlib\v1.11\App\src\App.jl:10 [inlined]
 [26] open(::App.var"#1#4", ::String, ::Vararg{String}; kwargs::@Kwargs{})
    @ Base .\io.jl:410
 [27] open
    @ .\io.jl:407 [inlined]
 [28] julia_main
    @ C:\Users\karlo\AppData\Local\Temp\jl_CAQOVC\share\julia\stdlib\v1.11\App\src\App.jl:9 [inlined]
 [29] main(ARGS::Vector{String})
    @ App C:\Users\karlo\AppData\Local\Temp\jl_CAQOVC\share\julia\stdlib\v1.11\App\src\App.jl:49
 [30] #invokelatest#2
    @ .\essentials.jl:1055 [inlined]
 [31] invokelatest
    @ .\essentials.jl:1052 [inlined]
 [32] _start()
    @ Base .\client.jl:536
during initialization of module HSL_jll
```

**Comment by JanisErdmanis** [comment]
I am currently unable to look into the issue properly. But regarding lazy artefacts, they were indeed not supported in the AppBundler v0.5 release; therefore, it may be worthwhile to check the main branch, where they have been fixed. 

```
InitError: could not load library "C:\Users\karlo\AppData\Local\Temp\jl_CAQOVC\share\julia\stdlib\v1.11\HSL_jll\override\bin\x86_64-w64-mingw32-libgfortran5\libhsl.dll"
The specified module could not be found. 
```
Can you check the contents of the parent directory?

**Comment by KSepetanc** [comment]
No good news. Using main branch did not fix it and directory after Temp does not exist (after app execution at least).
Note that I am using Base.require instead of import to catch the error as import can not be in try block.

**Comment by amontoison** [comment]
We use the trick with the folder `override` in the official `HSL_jll.jl`.
If you need an update of the path for making it relocable, I can change it for the next official release.

**Comment by amontoison** [comment]
@KSepetanc You will need to explain me what to change and also if it is possible...

**Comment by KSepetanc** [comment]
Probably I could provide better answer if I understood how current solution works (I did inspect it, but it is complicated).

As far I know, there are 3 things related to this.

One is `pkgdir(@__MODULE__)` which should provide relocatable path once joined with relative address within the package. This Janis mentions few comments above.

Second is using RelocatableFolders.jl. Folder and all of its files and subdirs can be made relocatable using `const SUBDIR = @path joinpath(ASSETS, "subdir")` . Files are accessed by simply joining path with SUBDIR.

The third is using artifacts. Aftifacts are intended way to distribute platform specific files. However, that might not be applicable here due to distribution restrictions. I am not sure what happens currently with artifacts in official package as they are still there, but somehow overriden. `overrides.toml` for artifacts does exits in Julia but it is not in the package but in `.julia`. One way would be to just use different artifacts for official package.

Considering you already have everything working only with baked in path, maybe option 1 would require least changes, but I am not sure. Personally, I once used RelocatableFolders and can confirm that works so it is possible. Maybe Janis can provide his expertise on this aspect. I am not sure if this is sufficient guidelines. I will help as much I can.

**Comment by KSepetanc** [comment]
@JanisErdmanis thank you for your reply. I spent most of the day researching how to deal with this. I agree `RelocatableFolders.jl` is really ugly hack.

The thing is I don't see how `pkgdir(@__MODULE__)` approach can work either. PackageCompiler for non Julia code just binds artifacts. Using current HSL_jll implementation, once compiled, .dll-s from overrides folder are missing. Just the ones from artifacts are there so while it may work with current AppBundler as it copies package source, I don't see how could it work with PackageCompiler.

Instead, I read that if there is `deps/build.jl` it will be run by Pkg at install. That file can avoid using artifact's download by copying the artifact to `.julia/artifacts`. From there on, artifacts system will find it already installed and link against it normally (so artifact download directive in toml can be skipped). Somehow it seems artifact system should be used (is intended for that) and it can be 'hacked' using `deps/build.jl`. However, HSL_jll is created using BinaryBuilder and I do not know if these custom changes are acceptable to Alexis.

**Comment by KSepetanc** [comment]
I suppose you meant:  `julia --startup-file=no --project=. -e "using MyApp"`

The GUI app precompiles, GUI opens. close button closes it and no residual Julia left. Reruning works as expected (no stacking).

Conceptually, the GUI main is this:

```
module App

using QML, myPackage


myPackage.myF(x::QML.QStringAllocated) = myPackage.myF(String(x))


function julia_main()::Cint
    @qmlfunction myF
	loadqml(joinpath(Base.pkgdir(@__MODULE__), "src/qml/Main.qml"))
	exec() 
    return 0
end


function (@main)(ARGS)
    return julia_main()
end


export main


end # module App
```

**Comment by JanisErdmanis** [comment]
Where do you see this structured view? I monitored the exit with ResourceMonitor

**Comment by KSepetanc** [comment]
Processes section of the default task manager

<img width="954" height="578" alt="Image" src="https://github.com/user-attachments/assets/fa95c301-a55e-4c3d-9945-13babe817a90" />

**Comment by JanisErdmanis** [comment]
Ok. I will have a look there

**Comment by KSepetanc** [comment]
Thank you for acknowledging. I don't need quick solution, but that it will be done means a lot. I will open an issue for this as suggested.

To comment on JuliaC, I gave it a try again and it works very good without a trim. Good decision for future upgrade. My current and biggest Julia issue is nasty compile problem that GPU instruction leak as CPU instructions. Maybe even some GPU instructions are silently dropped. The issue is posted at GPUCompiler, but probably should be posted at Julia itself. I am not compiler expert so only limited what I can do (mostly raise awareness and act as tester).
